### ISSUE TITLE
[BUG] Send email can't be used with attachment or with multiple fields (eg. multiple tos)

### ISSUE THREAD

**Issue by AhmedAlic** [infobip-community/infobip-api-node-sdk#30]
**Describe the bug**
This SDK doesn't support attachment or multiple fields usage over Send email endpoint. Problematic line is in forming FormData in FormDataBuilder function [here](https://github.com/infobip-community/infobip-api-node-sdk/blob/main/src/utils/form-data.ts).

**To Reproduce**
I used [Code example](https://github.com/infobip-community/infobip-api-node-sdk#code-example) to form an request that looks something like this:
```
let infobip = new Infobip({
            baseUrl: "https://api.infobip.com",
            apiKey: "API_KEY",
            authType: AuthType.ApiKey,
});

let response = await infobip.channels.email.send({
     to: "test@gmail.com",
     from: "test@infobip.com",
     subject: "Testing API Node SDK",
     text: "Hello World from API Node SDK",
     attachment: fs.readFileSync('/home/aalic/Downloads/1MB_test_file.pdf', "utf8")
 });
console.log(response);
```
Following code returns error message saying:
```
%%EOF' for CHID 'null'. Default message -> Failed to convert property value of type 'java.lang.String' to required type 'java.util.List' for property 'attachment'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.springframework.web.multipart.MultipartFile' for property 'attachment[0]': no matching editors or conversion strategy found
```

I used one more example to see if attachment should be passed as an array of attachments as described in API docs:
```
let infobip = new Infobip({
            baseUrl: "https://api.infobip.com",
            apiKey: "API_KEY",
            authType: AuthType.ApiKey,
});

let response = await infobip.channels.email.send({
     to: "test@gmail.com",
     from: "test@infobip.com",
     subject: "Testing API Node SDK",
     text: "Hello World from API Node SDK",
     attachment: [fs.readFileSync('/home/aalic/Downloads/1MB_test_file.pdf', "utf8")]
 });
console.log(response);
```
This code returns similar error:
```
%%EOF' for CHID 'null'. Default message -> Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.web.multipart.MultipartFile' for property 'attachment[0]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'java.lang.String' to required type 'org.springframework.web.multipart.MultipartFile' for property 'attachment[0]': no matching editors or conversion strategy found
```

Another issue is forming an request with multiple fields, example would be with multiple to's
```
let infobip = new Infobip({
            baseUrl: "https://api.infobip.com",
            apiKey: "API_KEY",
            authType: AuthType.ApiKey,
});

let response = await infobip.channels.email.send({
     to: ["test1@gmail.com", "test2@gmail.com"],
     from: "test@infobip.com",
     subject: "Testing API Node SDK",
     text: "Hello World from API Node SDK"
 });
console.log(response);
```
This returns me that validation fails with message:
```
Error: email.to must be a string.
```

**Expected behavior**
I expected for these request to pass with status 200. When I try to transform code from Postman with following examples, Postman converts them to this:

```
const axios = require('axios');
const FormData = require('form-data');
const fs = require('fs');
let data = new FormData();
data.append('from', 'test@infobip.com');
data.append('to', 'test1@gmail.com');
data.append('to', 'test2@gmail.com');
data.append('subject', 'Test request with attachment and multiple to's');
data.append('text', 'Plain text');
data.append('attachment', fs.createReadStream('/home/aalic/Downloads/1MB_test_file.pdf'));

let config = {
  method: 'post',
  url: 'https://api.infobip.com/email/3/send',
  headers: { 
    'Authorization': 'API_KEY', 
    ...data.getHeaders()
  },
  data : data
};

axios.request(config)
.then((response) => {
  console.log(JSON.stringify(response.data));
})
.catch((error) => {
  console.log(error);
});
```
This code should work and SDK should be fixed to work in similar way.

**Tested using:**
 - OS: [Ubuntu 22.04.2 LTS]
 - NodeJS v16.20.0

**Comment by pedrosimoessss** [comment]
Just some additional information: The java error on Infobip's transaction log is because we were creating a buffer form data property like `formData.append('attachment', bufferValue)`. This won't work with `form-data`, it needs to be `formData.append('attachment', bufferValue, { filename: 'foo.pdf' })`. Seems like the SDK also needs to take into account the attachment's file name as well.

**Comment by ukmadlz** [comment]
> Just some additional information: The java error on Infobip's transaction log is because we were creating a buffer form data property like `formData.append('attachment', bufferValue)`. This won't work with `form-data`, it needs to be `formData.append('attachment', bufferValue, { filename: 'foo.pdf' })`. Seems like the SDK also needs to take into account the attachment's file name as well.

I've attempted to allow for this in PR #31 with an object containing the file contents & it's name. Welcome to review

**Comment by ukmadlz** [comment]
I believe the merge of #31 fixes this, if the problem persists please raise the issue again
